### ISSUE TITLE
Import map help

### ISSUE THREAD

**Issue by danimydev** [hashrock/tabler-icons-tsx#10]
Hi, is there I way I can set an alias on Deno.json import map and then import the icons im going to use?

```json
{
  "imports": {
    "tabler-icons": "https://deno.land/x/tabler_icons_tsx@0.0.3"
  }
}
```

And then 

```typescript
import { IconBrandGithub, IconBrandFacebook } from "tabler-icons";
```

**Comment by hashrock** [comment]
bit longer, but it can be used like that:

```
"$tabler_icons/": "https://deno.land/x/tabler_icons_tsx@0.0.3/tsx/"
```

```
import IconArrowRight from "$tabler_icons/arrow-right.tsx";
```

Some icon libraries have index.tsx and gathers all imports for ease, but since the bundle becomes bloated with unused icons, I designed tabler_icons_tsx to import each file one by one.

**Comment by danimydev** [comment]
Oh that makes full sense, yeah agree, probably 80% of icons are not used in most cases. Thanks for the hint!
