### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by quick007** [hashrock/tabler-icons-tsx#12]
Hi, it looks like this package is missing some icons from tabler. 

I stumbled upon these while making my project:
![image](https://github.com/hashrock/tabler-icons-tsx/assets/69743171/8dff9a1e-7469-43ef-b1ec-d32c29944738)

But there's probably more as well

**Comment by timreichen** [comment]
It seems that there are more icons missing:

[calendar-week](https://tabler-icons.io/icon/calendar-week)
[calendar-month](https://tabler-icons.io/icon/calendar-month)
[calendar-clock](https://tabler-icons.io/icon/calendar-clock)

There might be more
