### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by timreichen** [hashrock/tabler-icons-tsx#14]
Ref https://github.com/hashrock/tabler-icons-tsx/issues/12#issuecomment-1818003869

It seems that there are more icons missing:

[calendar-week](https://tabler-icons.io/icon/calendar-week)
[calendar-month](https://tabler-icons.io/icon/calendar-month)
[calendar-clock](https://tabler-icons.io/icon/calendar-clock)

**Comment by hashrock** [comment]
addressed with https://github.com/hashrock/tabler-icons-tsx/commit/42074979c66c01f9c0b8f0eed5ddef94d70a3a06
