### ISSUE TITLE
It goes extremely slow

### ISSUE THREAD

**Issue by evilmonkey19** [hashrock/tabler-icons-tsx#15]
Hi!

Thank you very much for such awesome work! I have been using it for some time. However, for some reason which i don't understand, it takes roughly 30 seconds to load many times. Is it because you look for all the icons before sending to the client?

Thanks!

**Comment by hashrock** [comment]
I think it's probably taking time due to the cold start of deploy + fresh(it executes esbuild-wasm). Maybe I should try the AoT mode in Fresh.

**Comment by hashrock** [comment]
@evilmonkey19 
I turned AoT mode on. It should have improved somewhat, so please give it a try.

**Comment by evilmonkey19** [comment]
OMG!!! Now it goes WAY BETTER. Thank you a lot for the huge improvement. Now it only takes a few seconds which is perfectly fine (at least for me).

Thanks a lot!!! :D 

P.D: I used it a lot in my projects when i use Deno-Fresh. The API is simple and clear! The projects i mention are publicly available so can check them out.
