### ISSUE TITLE
tabler icon import failing

### ISSUE THREAD

**Issue by crowlsyong** [hashrock/tabler-icons-tsx#17]
(originally posted [here](https://github.com/denoland/deno/issues/23948#issue-2311421845) but I was told to come here instead)

### Environment

(it's all Deno)
Version: Deno 1.43.5 (release, aarch64-apple-darwin)
v8 12.4.254.13
typescript 5.4.5
Fresh Framework
Deno KV

### Issue
cannot import IconCopyCheck with `https://deno.land/x/tabler_icons_tsx@0.0.5/tsx/copy-check.tsx`
Visiting that url appears to show a 404 not found inside the area where the data should be. I My have run into other Icons which don't import, but I forgot to write them down. I will comment on this if I find another one. 

Tell me what else you need from me and I will get you the info as best I can. If this is a Fresh Framework issue, let me know and I'll post this there instead.

I am using other icons that work though, for example, these all work for me:
`import IconQrcode from "https://deno.land/x/tabler_icons_tsx@0.0.5/tsx/qrcode.tsx";`

`import IconHttpDelete from "https://deno.land/x/tabler_icons_tsx@0.0.5/tsx/http-delete.tsx";`

`import IconCopy from "https://deno.land/x/tabler_icons_tsx@0.0.5/tsx/copy.tsx";`

`import IconEdit from "https://deno.land/x/tabler_icons_tsx@0.0.5/tsx/edit.tsx";`

`import IconDeviceFloppy from "https://deno.land/x/tabler_icons_tsx@0.0.5/tsx/device-floppy.tsx"; `

**Comment by kellnerd** [comment]
I think this is effectively the same issue as #16, the modules have to be updated from the latest Tabler icons release to include all of the newer icons.

**Comment by crowlsyong** [comment]
Oh! Brilliant. I'll close this.
