### ISSUE TITLE
How to import using the import_map.json file?

### ISSUE THREAD

**Issue by klerpi** [hashrock/tabler-icons-tsx#3]
Hi! I've been trying to use my import map so I don't have to write the full URL everytime I use an icon but it doesn't seem to work. Is there something extra to do when importing this module with import_map.json?

**Comment by ghost** [comment]
you can do something like this:
```jsonc
// import_map.json
{
  "imports": {
    "tabler-icons-tsx/": "https://deno.land/x/tabler_icons_tsx@0.0.2/tsx/"
  }
}
```
```ts
import IconBrandDeno from "tabler-icons-tsx/brand-deno.tsx"
```

Edit: maybe has or would be better to have a `mod.ts` that exports every icon and you just do:
```js
import { IconBrandDeno, IconLemon2 } from "tabler-icons-tsx"
```

**Comment by klerpi** [comment]
Awesome! Thank you very much
