### ISSUE TITLE
Icon on deno-website differs from the official website

### ISSUE THREAD

**Issue by rimzudev** [hashrock/tabler-icons-tsx#4]
While looking for a star icon I stumbled upon the jewish-star icon on: https://tabler-icons-tsx.deno.dev/
```
<path d="M9.748 5.753l2.252 -3.753l3 5h6l-3 5l3 5m-4 0h-2l-3 5l-3 -5h-6l3 -5l-3 -5h4" />
<path d="M3 3l18 18" />
```
This differs from the website: https://tabler-icons.io/i/jewish-star
```
<path d="M12 2l3 5h6l-3 5l3 5h-6l-3 5l-3 -5h-6l3 -5l-3 -5h6z"></path>
```

In my eyes this should look more like 2 triangles or at least without the dash like on the main website.

Disclaimer:
I am no expert but just trying to help if something went by unnoticed until now. Sorry if I am missing out something.

**Comment by hashrock** [comment]
oh this is strange. What we doing here is only download zip from tabler-icons repo and convert it to tsx.

https://github.com/hashrock/tabler-icons-tsx/blob/main/util/convert-all.ts

Maybe the original file in old tabler-icons we used was wrong, or something happened during the tsx conversion. Thanks for reporting this!

**Comment by hashrock** [comment]
![image](https://user-images.githubusercontent.com/3132889/223852020-ef9649e5-448b-4cca-96cb-66c5eee3f62e.png)

ok looks like original version's failure.

**Comment by toastoaster** [comment]
No problem, glad I could help and thanks for fixing it immediately!

**Comment by rimzudev** [comment]
No problem, glad I could help and thanks for fixing it immediately!
