### ISSUE TITLE
Is version 0.0.4 released officially?

### ISSUE THREAD

**Issue by ryuapp** [hashrock/tabler-icons-tsx#8]
[tabler_icons_tsx@0.0.4](https://deno.land/x/tabler_icons_tsx@0.0.4) is released in deno.land/x.
But that release note is not found in [Releases](https://github.com/hashrock/tabler-icons-tsx/releases).

Is version 0.0.4 released officially?

**Comment by hashrock** [comment]
It's been released! I forgot to put the release notes 😆
